- hosts: bootstraps
  remote_user: centos

  vars_prompt:
    - name: "dcos_password"
      prompt: "What is your DC/OS cluster password for your initial user?"

  tasks:
    # generating CA stuff
    - name: download dcos CLI
      get_url:
        url: "https://downloads.dcos.io/cli/releases/binaries/dcos/linux/x86-64/0.8.0/dcos"
        dest: "/home/centos"
        mode: 0644

    - name: copy CLI to /usr/local/bin and make it executable
      become: true
      copy:
        src: "/home/centos/dcos"
        dest: "/usr/local/bin/dcos"
        mode: 0755
        remote_src: yes

    - name: setup cluster
      shell: "dcos cluster setup --insecure https://{{ dcos.config.master_list[0] }} --username {{ dcos.config.superuser_username }} --password {{ dcos_password }}"

    - name: test command to run
      command: "dcos node"