- hosts: bootstraps
  remote_user: centos
  tasks:
    - name: "create workspace folders"
      file:
        path: "{{ item }}"
        state: directory
      loop: [ "/home/centos/workspace", "/home/centos/workspace/dcos-monitoring" ]

    - name: "create dcos-monitoring service account keypair"
      command: "dcos security org service-accounts keypair /home/centos/workspace/dcos-monitoring/dcos-monitoring-private-key.pem /home/centos/workspace/dcos-monitoring/dcos-monitoring-public-key.pem"

    - name: "create dcos-monitoring service account"
      command: "dcos security org service-accounts create -p /home/centos/workspace/dcos-monitoring/dcos-monitoring-public-key.pem -d 'dcos-monitoring' dcos-monitoring-principal"

    - name: "create dcos-monitoring service account secret"
      command: "dcos security secrets create-sa-secret --strict /home/centos/workspace/dcos-monitoring/dcos-monitoring-private-key.pem dcos-monitoring-principal dcos-monitoring/service-account-secret"

    # Permissions plethora
    - name: "dcos-monitoring permissions"
      command: "{{ item }}"
      loop:
        - "dcos security org users grant dcos-monitoring-principal dcos:adminrouter:ops:ca:rw full"
        - "dcos security org users grant dcos-monitoring-principal dcos:adminrouter:ops:ca:ro full"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:agent:framework:role:slave_public read"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:framework:role:dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:framework:role:slave_public read"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:framework:role:slave_public/dcos-monitoring-role read"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:framework:role:slave_public/dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:reservation:principal:dcos-monitoring-principal delete"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:reservation:role:dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:reservation:role:slave_public/dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:task:user:nobody create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:volume:principal:dcos-monitoring-principal delete"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:volume:role:dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal dcos:mesos:master:volume:role:slave_public/dcos-monitoring-role create"
        - "dcos security org users grant dcos-monitoring-principal 'dcos:secrets:default:/dcos-monitoring/*' full"
        - "dcos security org users grant dcos-monitoring-principal dcos:secrets:list:default:/dcos-monitoring read"

    - name: "prepare dcos-monitoring-options.json"
      copy:
        dest: "/home/centos/workspace/dcos-monitoring/dcos-monitoring-options.json"
        content: |
          {
              "service": {
                "service_account_secret": "dcos-monitoring/service-account-secret",
                "service_account": "dcos-monitoring-principal"
              },"prometheus": {
                "cpus": 2.0,
                "mem": 2048
              }, "grafana": {
                "cpus": 1.0,
                "mem": 1024
              }
          }

    - name: "Install dcos-monitoring"
      command: "dcos package install dcos-monitoring --options=/home/centos/workspace/dcos-monitoring/dcos-monitoring-options.json --yes"